---
- name: playbookB
  gather_facts: true
  become: true
  hosts: nodeB
  vars:
    postgresql_version: "14"
    postgresql_bin_path: "/usr/lib/postgresql/{{ postgresql_version }}/bin"
    postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
  roles:
    - roleB